apiVersion: v1

kind: Service

metadata: 

  name: flaskapp-deployment

spec:

  selector:
    app: flaskapp

  ports:
    - protocol: TCP
      port: 80 
      targetPort: 9300

  type: LoadBalancer

---

apiVersion: apps/v1

kind: Deployment

metadata: 

  name: flaskapp-deployment

spec: 

  replicas: 3

  selector:

     matchLabels:

       app: flaskapp

  template:

    metadata:

      labels:

        app: flaskapp

    spec:

      containers:

      - name: flaskapp

        image: cagil04/flask_app:latest
        imagePullPolicy: Always
        ports:

        - containerPort: 80

      imagePullSecrets:

      - name: regcred

