apiVersion: v1

kind: Service

metadata:

  name: kubelab-mssql

spec:

  selector:

    app: kubelab-mssql

  ports:

    - nodePort: 31500

      protocol: TCP

      port: 14333

      targetPort: 14333

  type: NodePort

---

apiVersion: apps/v1

kind: Deployment

metadata:

  name: mssql-deployment

spec:

  replicas: 1
  
  selector:

    matchLabels:

      app: kubelab-mssql

  template:

    metadata:

      labels:

        app: kubelab-mssql

    spec:

      terminationGracePeriodSeconds: 10

      containers:

      - name: mssql

        image: cagil04/kubelab-mssql-2019:latest

        ports:

        - containerPort: 14333

        env:

        - name: ACCEPT_EULA

          value: "Y"

        - name: SA_PASSWORD

          valueFrom:

            secretKeyRef:

              name: mssql

              key: SA_PASSWORD

        volumeMounts:

        - name: mssql-persistent-storage

          mountPath: /var/opt/mssql

      volumes:

      - name: mssql-persistent-storage

        persistentVolumeClaim:

          claimName: kubelab-mssql-pvc
