version: '2.2'

services:

  db:

    container_name: kubelab-sqlserver
    build:
      context: .
      dockerfile: Dockerfile
    hostname: kubelab-sqlserver2019

    environment:
      MSSQL_SA_PASSWORD: "PaSSw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"

    ports:
      - "14333:1433"

    mem_limit: 10Gb

